### ISSUE TITLE
Correct for adding a payment gateway

### ISSUE THREAD

**Issue by CptMeatball** [responsiv/pay-plugin#20]
I'd like to add `omnipay/ideal` to the payment gateways, but I can't seem to figure out how to do this. Is there any documentation for this?

**Comment by MilosStanic** [comment]
Besides adding more omnipay payment libraries, which is certainly interesting, I was interested in making my own payment plugin for ePay.dk, because my customer demands it.

I investigated the /paymenttypes folder and found that implementing a new method would probably be pretty easy in a canonical way, using other payment methods as example. However, the problem I'm currently seeing is registering the new payment method with Responsiv.Pay plugin. 

I see there is a `registerPaymentGateways` method returning an array of payment method classes associated with their codes. I don't see a way of extending the plugin to add an item to this array. 

It is really important that @daftspunk  opens a way for us to extend this plugin and provide more payment methods for October users. 

Thanks.

**Comment by daftspunk** [comment]
Really simple stuff here, to create a new gateway:

1. Add a `paymenttypes` folder to your plugin, copy the structure from this one
1. Define a `registerPaymentGateways` method in your plugin file, copy [syntax from this one](https://github.com/responsiv/pay-plugin/blob/master/Plugin.php#L97-L112).

However, at this early stages, it might be better to just submit a Pull Request? Up to you.

**Comment by MilosStanic** [comment]
Yeah, that is very simple. I figured out the first step myself, already. 
Now, all I have to do is implement the payment method for ePay.dk :) .
No problem making a PR, it's just that nobody is interested in ePay.dk, except my client :) . Only one library on the whole github, and it's a Ruby one. 

Thanks for the quick reply.

**Comment by Almusamim** [comment]
@MilosStanic I think there would be many people interested in having Epay.dk gateway which is now Bambora.
