### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jestherthejoker** [responsiv/pay-plugin#46]
Installation on October CMS won't work using the plugin manager doesn't work for me.

Does the ff is required to install the `pay-plugin`:
- Responsiv.Currency
- RainLab.User
- RainLab.Location

**Comment by LukeTowers** [comment]
@acasar why is it trying to load omnipay/common 3.0?

**Comment by acasar** [comment]
@LukeTowers I'd say omnipay/braintree is the one requiring it: https://github.com/thephpleague/omnipay-braintree

We are requiring "omnipay/braintree": "~2.0" which by the looks of it doesn't even exist: https://github.com/thephpleague/omnipay-braintree/releases

**Comment by LukeTowers** [comment]
@acasar are there any problems with upgrading the dependencies?

**Comment by acasar** [comment]
@LukeTowers We should update composer.json to fix this issue. Yesterday I started using my fork, where I made this change: https://github.com/acasar/pay-plugin/commit/01348756aea3b1897f08622131274cdcfb66909d

The issue is that with this commit 13 days ago https://github.com/thephpleague/omnipay-braintree/commit/74a8ed2773c6185226b4d845a11e18e29c15b42b omnipay/braintree upgraded to omnipay/common 3.0. But it's not tagged yet, so it normally shouldn't cause any issues.

But since we're requiring version 2.0 of omnipay/braintree (which doesn't even exist), we are always getting dev-master with all latest commits. So 13 days ago, when this change was made, responsiv/pay could not be installed using composer any more. And I guess installing through October's package manager will soon have problems too.

**Comment by LukeTowers** [comment]
@acasar installing through the marketplace won't be an issue, it precomiles the builds which includes the libraries in the plugin /vendor folder at compile time so no worries there. Feel free to make a PR here with the required changes. 

What's the compatibility of just using 3.0 vs 1.0?

**Comment by acasar** [comment]
@LukeTowers Created a PR here: https://github.com/responsiv/pay-plugin/pull/48

> installing through the marketplace won't be an issue, it precomiles the builds which includes the libraries in the plugin /vendor folder at compile time so no worries there.

Still, it will probably fail on the next recompile, since it would be unable to install composer dependencies.

> What's the compatibility of just using 3.0 vs 1.0?

You mean omnipay/common 3.0 vs 2.0, that we are using now? It has a few breaking changes so some other changes would be needed as well.

**Comment by acasar** [comment]
@LukeTowers When I have a bit more time I can try and tackle this. For now, fixing braintree dependency seems to have solved the issue. Thanks!

**Comment by daftspunk** [comment]
Moved to #66
