### ISSUE TITLE
Cannot install with with symfony/http-foundation v4.4

### ISSUE THREAD

**Issue by daftspunk** [responsiv/pay-plugin#66]
Problem: **omnipay/common** needs to be updated

```
  Problem 1
    - omnipay/common[v2.0.0, ..., v2.5.0] require symfony/http-foundation ~2.1 -> found symfony/http-foundation[v2.1.0, ..., 2.8.x-dev] but the package is fixed to v4.4.20 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - omnipay/common[v2.5.1, ..., 2.5.x-dev] require symfony/http-foundation ~2.1|~3.0 -> found symfony/http-foundation[v2.1.0, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev] but the package is fixed to v4.4.20 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - responsiv/pay-plugin dev-master requires omnipay/stripe ~2.0 -> satisfiable by omnipay/stripe[v2.0.0, ..., 2.x-dev].
    - omnipay/stripe[v2.0.0, ..., 2.x-dev] require omnipay/common ~2.0 -> satisfiable by omnipay/common[v2.0.0, ..., 2.5.x-dev].
    - Root composer.json requires responsiv/pay-plugin dev-master -> satisfiable by responsiv/pay-plugin[dev-master].
```

**Comment by tomaszstrojny** [comment]
Hi @daftspunk,

I was thinking about solving this issue but it seems to be a bigger thing than any of us will ever have time for, I think ;) That's why I am thinking about handling the issue in a slightly different way than updating all the gateways.

What do you think about splitting this plugin into two: `Responsiv.Pay` and `Responsiv.PayGateways`, or something similar? What I'm thinking about, is leaving the functionality of the current plugin to be split into two plugins in such a way, that the first one has only the "Offline" gateway with all the required interfaces and handlers. The second one could register all the gateways in the current form. After digging into this code a little deeper, I see that it's achievable and fairly easy.

I know it's not a "solution" per se but I think that this could give the `Responsiv.Pay` plugin independence on the gateways which APIs are updating and living their lives. Thanks to that `Responsiv.Pay` would only need to be compatible with October and this could increase the community's confidence in providing support for gateways required in their projects.

If you like the idea I can handle this in this plugin as well as creating the new one.

Send me your thoughts,

Tomasz Strojny

**Comment by daftspunk** [comment]
Hey @tomaszstrojny 

I think it's just easier to fix or disable the broken payment types for now. This plugin was designed to ship with some working examples for people to learn.

**Comment by tomaszstrojny** [comment]
Hi @samgeorges,

I see although I don't think splitting it into two plugins would interrupt this mission. People would still have working examples in a separate plugin. Anyway, I guess you just don't want to do that which is fine, it's your plugin.

I'm thinking about fixing or disabling it, as you suggest but can't imagine it, yet.

Disabling it would probably require some hacks in the composer config to not pull the dependencies. Am I correct? Of course, I can use my fork without the dependencies in the plugin (as I'm sure I don't want to use any of the provided gateways in my project) but I don't think it's a good way to go.

Fixing it would probably require me to bite the docs of PayPal, Stripe, Skrill, and Braintree, register an account in their services for testing purposes, and try to play with every single one of them separately. As I said, I don't plan to use any of these in my project so it seems to me like a huge unneeded (from my perspective) work. Do you have any suggestions for me to work on it more efficiently?

What is more, APIs are upgrading, I need to know if we want to keep the old APIs in the plugin, or should we upgrade all the references to match the newest ones?

Thanks!

Tomasz Strojny

**Comment by daftspunk** [comment]
Yes, you're right. Preference not to maintain two plugins is the key reason.

Simply remove the troublesome payment types from the `registerPaymentGateways` method in the plugin registration file. Then remove the broken composer dependency as well.

**Comment by tomaszstrojny** [comment]
Hi @daftspunk ,

I'm not sure I understood you correctly. You mean I could do it as a PR to your plugin? If so, wouldn't it really be easier to move the deprecated payment gateways to a separate plugin and mark its repository as archived? This would free you from maintaining the gateways and people could still use it as a reference.

I think I could handle Stripe and PayPal to use their official PHP packages (as you suggest, without Omnipay) and almost all the current gateways would be moved to the second plugin.

Feel free to correct me if I got anything incorrectly. If what I wrote makes sense to you, just create the repo for the second plugin and let me know, I'll handle the rest.

Thanks, 

Tomasz Strojny

**Comment by daftspunk** [comment]
I meant this: https://github.com/responsiv/pay-plugin/commit/dc048f3cac0835bbcff9186f9f23e17de860e263

Now the plugin can be installed, at least.

**Comment by tomaszstrojny** [comment]
Haha! Ok :smile: 

I thought we were talking about something bigger, with a "breaking changes" note or something. Anyway, I like the way you handled that - the commit message is self-explanatory :heart: 

There is a possibility that I'll be integrating the plugin with Stripe soon. If so, do you want me to do it in the plugin and create a PR with this?

Thanks for all your work!

BTW, doesn't it make this issue "solved"?

**Comment by daftspunk** [comment]
Yes, a PR that uses the Stripe SDK and not Omnipay would be great.

You're right, let's close this. Thanks!
